### ISSUE TITLE
When will the turrets be buyable in the terminal?

### ISSUE THREAD

**Issue by UmaLPZ** [SquidyBallinx11011/LethalCompany-ShipTurrets#2]
Hey, really interested in this mod. Just waiting for the update where they need to be purchased before they are attached to the ship. I want to keep things more balanced and make ship turrets more of a progression thing rather than starting with them from the beginning of a run.

No rush on this though. Just wanted to see if there is an eta or anything.

**Comment by SquidyBallinx11011** [comment]
Hi, I did work on this a little before, but only managed it as far as making it work for the host only. I could not work out the netcode for clients to do it through the terminal. Do you think it would be useful as a host only option for now?

**Comment by UmaLPZ** [comment]
Does that mean only the host would be able to purchase the turrets? As long as the turrets only work if the host purchases them, I think it would be fine.

**Comment by SquidyBallinx11011** [comment]
Yes, I can add in host to purchase but enabling it for all clients was difficult. I'll add in a config option for locking it from default on to host enabled on terminal.

**Comment by SquidyBallinx11011** [comment]
Updated and live as version 1.0.2. Let me know if it breaks anything. (One thing I noticed is after buying it, it will change the config file to true, so it's not currently tied to saves but your games config file.)

**Comment by UmaLPZ** [comment]
Thank you so much! I didn't get to try it until tonight but it looks like it interferes with the FairAI mod. Enemies will still set off mines thanks to FairAI, but turrets will only target enemies and not shoot. The turrets on the moons also didn't shoot me or anyone else playing. I left the friendly fire option off during our session.

I will note that I didn't get the opportunity to purchase the ship turrets and I didn't test the mod with friendly fire on. I'll try testing it sometime tomorrow and let you know if anything changes.

**Comment by UmaLPZ** [comment]
Alright finally got around to testing this out. Looks like turrets no longer shoot at players regardless of the "friendly fire option" being on or off. The turrets on the moons will still target players (and monsters thanks to FairAI) but will not shoot. The ship turrets will shoot enemies with no issues. They also target players regardless of the friendly fire option but again will not shoot players.

The other mods I use that could be interfering with turrets are the FairAI and Lategame Upgrades mods.

**Comment by SquidyBallinx11011** [comment]
If you are running other mods, especially ones effecting turret AI I can not garantee there won't be bugs.

Closing this thread as the original suggestion for terminal purchasing turrets has been added.
