### ISSUE TITLE
[Suggestion] What enemies to be allowed to shoot at

### ISSUE THREAD

**Issue by MetroidCatcher** [SquidyBallinx11011/LethalCompany-ShipTurrets#5]
What the title says, like if I don't like that they shoot Manticoils, Roaming Locusts or the Bees, because those are useless against, and it makes a horrible sound mess, if that is possible, that is.

**Comment by SquidyBallinx11011** [comment]
Turrets are hard-coded not to target Manticoils, Roaming Locusts or the Bees. I didn't think this was needed to be configurable so it's hard-coded.
