### ISSUE TITLE
Not working on latest version [v50]

### ISSUE THREAD

**Issue by AtomicJuno** [SquidyBallinx11011/LethalCompany-ShipTurrets#6]
The turrets will activate but then stay frozen in a non-attacking state on the latest version.

**Comment by AtomicJuno** [comment]
Sorry to send another message here , but is this mod still being worked on, or is it deprecated?

**Comment by SquidyBallinx11011** [comment]
Thanks for the reminder. I've rebuilt using the V50 files and it should be working now.

Download the latest version of ShipTurrets V1.0.4 from Thunderstore and let me know if it works.

**Comment by AtomicJuno** [comment]
Trying it now, thanks!

**Comment by AtomicJuno** [comment]
Works perfectly!
