### ISSUE TITLE
Mod doesnt works

### ISSUE THREAD

**Issue by azp23** [SquidyBallinx11011/LethalCompany-ShipTurrets#9]
Hi, looks like this awesome mod doesnt works with versions 60+. If it still supported, could u update it, pls?

**Comment by SquidyBallinx11011** [comment]
Hello friend.

I have rebuilt with the latest V60 files. It should now perform as before.

Let me know if it does not.

**Comment by azp23** [comment]
Hello, now it works perfectly, thank you for creating and supporting this cool mod!

Best wishes and good luck to you, bro
